### PR TITLE
[SWS-61] Dependencies: add testify

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by jotak** [comment]
oh wait I think there's a mistake

**Comment by jotak** [comment]
It's ok. My mistake was to import testify/assert instead of the whole testify packages (we would miss other packages like "mock").
It's good now.

**Comment by abonas** [comment]
@jotak please add a JIRA card reference

**Comment by jotak** [comment]
@abonas title edited (SWS-61)

**Comment by abonas** [comment]
> It's ok. My mistake was to import testify/assert instead of the whole testify packages (we would miss other packages like "mock").

does it mean we can't mock or now it was fixed?
> It's good now.

**Comment by jotak** [comment]
@abonas it's fixed, we *can* mock :-)

**Comment by pilhuhn** [comment]
It builds well, so I'll merge it.

**Pull request merged**
