### PR TITLE
SWS-205 show version of the UI

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This doesn't show a "about" box in the UI (obviously, that would have to go in swsui). But it goes log the version of the UI in swscore log.

Not sure if we want it to work like this, hence the DNM label.

We could publish a /status or /version endpoint for the UI to pull, but that seems kind of weird for the UI to ask the server what version it is. I would think swsui should have something in its own .js files that encode this info.

**Comment by josejulio** [comment]
> We could publish a /status or /version endpoint for the UI to pull, but that seems kind of weird for the UI to ask the server what version it is. 

Yes, that would be weird

> I would think swsui should have something in its own .js files that encode this info.

I can work on that, I'll create a jira for it.

**Comment by josejulio** [comment]
> Not sure if we want it to work like this, hence the DNM label, but at least this tells you what version of the UI is being served by swscore, so that is at least helpful.

I suppose it could be useful to have that information when building the docker image, knowing what swsui we are using.

**Comment by jmazzitelli** [comment]
@josejulio see SWS-205 JIRA

**Comment by jmazzitelli** [comment]
@josejulio assign that to you if you can put this information in the swsui itself

**Comment by jmazzitelli** [comment]
I took the DNM label off. Let's get people to review this simple PR and if it is OK, we can merge it.

Quick summary of what this is:

1) The Makefile determines what UI version it is packaging up and writes a file called version.txt in the root directory of the console build files.

2) The main Go file sws.go will simply read that file and log the UI version. So when you start the Go app, in the output log messages you will see the version of the UI it is serving up.

**Pull request merged**
