### PR TITLE
Add http client and tests

### PR DESCRIPTION
**Pull request by jmazzitelli**
~~This adds a convenience http client object useful to making http and https calls with basic or bearer token auth~~

This also tests that the API Server and Console endpoints are valid. Also tests https and auth.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
For some reason, sometimes the tests hang. I do not know why yet.

**Comment by lucasponce** [comment]
Before to add the security components.
What is our planned approach to this ?
I mean, what is the security of a non-secure component like Prometheus in our architecture ?
Just thinking loud, my first thought was trying to follow the security approach from Istio with Prometheus, instead to protect our endpoints I guess.
I don't want to trigger a big discussion on it, but just curious as I saw in the code the skeleton for that.

**Comment by jmazzitelli** [comment]
> Before to add the security components.
> What is our planned approach to this ?

Matt (or was it Heiko?) stated we are going to need to support at least https.

> I mean, what is the security of a non-secure component like Prometheus in our architecture ?

For the client-side piece (the http_client in this PR): this code doesn't require non-secured components to be secured. The http_client API in this PR supports requesting data from non-secured http and secured https and can support sending requests with no authentication, or with basic or bearer token authentication (I have unit tests testing all of those security options mentioned - see http_client_test.go and server_test.go). So whatever components we need to talk to, we can talk to them (they can be http or https, and can require basic or bearer token or nothing at all).

As for the server-side piece, the server does not assume any security requirements, though I believe (again, Matt or Heiko, I can't remember) did say we most likely need to support at minimum https. The server introduced in PR #8 and used by this API server in PR #11 can be secured over https or can be unsecured (http) through settings in configuration. It can also support simple BASIC auth or bearer token auth, or no auth at all (but it is a very simple implementation to start with). Again, configuration dictates the behavior and thus we can decide how we secure the server, if at all.

> Just thinking loud, my first thought was trying to follow the security approach from Istio with
> Prometheus, instead to protect our endpoints I guess.
> I don't want to trigger a big discussion on it, but just curious as I saw in the code the skeleton for that.

I left it all configurable so we can decide how we want to do it in the future. I didn't think we'd be able to get away with the Prometheus method ("we don't do security - you are on your own"). https support in the server, I think, is almost a requirement. Authenticating to the server with basic or bearer tokens I'm less sure of - but we have a simple implementation now in case we need to build that out. If we absolutely do not want it, we can rip out the basic/bearer token auth stuff pretty easily from the server.

**Comment by lucasponce** [comment]
Can be put this on hold and discuss it tomorrow ?
Basically I am working on the clients for k8s and p8s from SWS-90 JIRA.
It brings the libraries needed for communicating with the backends and embeds theirs http client layer as well.

So, if we needed in additional scenarios, good, but I guess we would have some overlap then.
Anyway, I guess just talking we can sync on we will need and if we have something redundant or not.

**Comment by jmazzitelli** [comment]
The reason for the existence of the http_client (for this PR) is so I can have them in the unit tests for the server (server_test.go). We can roll the http_client in a test-only file if we don't want to expose it.

**Comment by jmazzitelli** [comment]
Removed the http_client and the entire http package.

**Comment by lucasponce** [comment]
PR looks good to me.
It enhances configuration of the main server to support security credentials and also introduce standalone testing for the server.
I couldn't test locally the testing helpers but assuming Travis does that the code looks good.

**Comment by jmazzitelli** [comment]
A "make test" should be able to test this on your local box. That is what travis does, as well.

I need an actual review posted in this PR so it can be merged.  Don't be shy. :)

**Comment by jshaughn** [comment]
LGTM as well.

**Pull request merged**
