### PR TITLE
Fixing warnings / go vet

### PR DESCRIPTION
**Pull request by jotak**
- Vet: fix yaml tagging
(Go vet was reporting: struct field tag `,omitempty` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair)
- Good practice: document all exported functions
- Good practice: mixedCaps https://golang.org/doc/effective_go.html#mixed-caps
- Good practice: use consistent case for initials
( https://github.com/golang/go/wiki/CodeReviewComments#initialisms )

PS: topic opened internally to discuss about code style

### CODE REVIEW

**Comment by aljesusg** [comment]
LGFM,
GoLint report this kind of errors, we should add it

**Comment by jotak** [comment]
I've added more fixes

**Comment by jmazzitelli** [comment]
Just FYI: if we are enforcing coding styles at this early stage in the game, please just shoot me now.

**Comment by jotak** [comment]
@jmazzitelli not that I want to shoot you down! but it seems easier (at least to me) to learn good practices from the start, than learning with bad practices and later understanding I was doing it wrong, and having to change hundreds of LOC later. It doesn't seem such a big pain, is it?

**Comment by jmazzitelli** [comment]
having lint type processors is a pita - sorry, just my opinion, but I've been around long enough to know having to worry about getting my code to match some arbitrary coding style is inefficient and gets in the way - always.

**Comment by jotak** [comment]
This PR is not related to any option we choose about golint, so... can it be merged anyway?

**Comment by jmazzitelli** [comment]
Doesn't matter to me. There isn't any functionality change here, so it can be merged as is.

I'm extremely glad we now can see API and not Api and URL and not Url in variable names, because it is completely unreadable otherwise. :-p

**Pull request merged**
