### PR TITLE
gofmt format files with errors

### PR DESCRIPTION
**Pull request by aljesusg**
Gofmt throw errors only in this file @jmazzitelli

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Did you git pull to the latest master? Because when I do that, I get this:

```
$ git pull
Current branch master is up to date.
$ gofmt -s -l ./routing/routes.go  
./routing/routes.go
```

**Comment by jmazzitelli** [comment]
Same with sws.go:
```
$ gofmt -s -l ./sws.go 
./sws.go
```

**Comment by jmazzitelli** [comment]
My diffs:

routes.go:
```
-		Route{
+		{
```

and sws.go:

```
-		for _ = range signalChan {
+		for range signalChan {
```

**Comment by jmazzitelli** [comment]
```
$ go version
go version go1.9.3 linux/amd64
```

I wonder if its a go version different - gofmt might behave different across versions? What version do you have?

**Comment by aljesusg** [comment]
Yes.... I am gonna update my go version, maybe we should check the go version in the makefile

**Comment by aljesusg** [comment]
The same result with go 1.9.4, This is amazing ^^

**Comment by jmazzitelli** [comment]
```
$ git rev-parse HEAD
9a0b5e95b7c4a1cc5fa9cd0bc3a9721ec3fd1fde
```
That is where my master branch is. Is that the same as you @aljesusg  -- just making sure we are working on the same source.

**Comment by aljesusg** [comment]
The same results in 1.8 and 1.9.3 I don't know why me gofmt result is different. Anyway  @jmazzitelli we should check in Makefile the version of go because travis is working with 1.8.3. I don't know if working with different versions is a good idea.

**Comment by aljesusg** [comment]
Yes, the same version in master, and this is the git log in the branch
```bash
commit 24dd62ddac15a0d668e036ae00eb5ee9100cac4d
Author: Alberto Jesus Gutierrez Juanes <aljesusg@gmail.com>
Date:   Thu Feb 15 23:58:45 2018 +0100

    gofmt format files with errors

commit 9a0b5e95b7c4a1cc5fa9cd0bc3a9721ec3fd1fde
Author: Xavier Canal i Masjuan <xeviknal@gmail.com>
Date:   Thu Feb 15 21:22:06 2018 +0100

    Allow deployments to be successfull using minishift (#25)
```

**Comment by jmazzitelli** [comment]
OK, I'm going to merge this PR. Let's see what happens with travis with your other PR.

We'll worry about fixing on a go version later.

**Comment by aljesusg** [comment]
Yes, I need to rest, in Spain is so late ^^

**Pull request merged**
