### PR TITLE
Make task for check go version

### PR DESCRIPTION
**Pull request by aljesusg**
This test in build that at least you have the go version of travis

### CODE REVIEW

**Comment by aljesusg** [comment]
Not merge !! I need to change the error message to warning and not exit 1. Can someone put label not nege?

**Comment by jmazzitelli** [comment]
> need to change the error message to warning and not exit 1

With this PR, if someone tries to build with an older version of Go, the build will fail. Is that correct?

Is that not what we want to happen?

**Comment by aljesusg** [comment]
Yes, we wanna show a warning message if the version is lower 1.8.3 (Travis build). Should we stop in the build if go version is lower?

**Comment by jmazzitelli** [comment]
@aljesusg I think we should stop the build if someone tries to build with go 1.7. I think we want people using 1.8. In that case, yes, stop the build. If we want to restrict the version to something on the patch level (1.8.x), I do not know. But as long as travis passes with the 1.8.3 check, we can require at least 1.8.3 (though I do not know if it matters if someone wants to use 1.8.1 or 1.8.2).

In any event, I think it is fine if we stop the build. GoLang is up to 1.9.x, so asking people to be on 1.8 should not be a problem.

**Comment by aljesusg** [comment]
Ok so We can merge ^^ Thanks @jmazzitelli

**Comment by abonas** [comment]
@aljesusg is the required Go version clear from the readme?

**Comment by jmazzitelli** [comment]
In the README, we state "(1) Go Programming Language which must be at least version 1.8"

**Comment by aljesusg** [comment]
No..We should add in readme something about supported versions. Do you agree?

**Comment by abonas** [comment]
exactly @aljesusg  :)
readme says 1.8 and here it enforces 1.8.3.

**Comment by aljesusg** [comment]
I did the change in Readme

**Comment by aljesusg** [comment]
Thanks @jmazzitelli & @abonas

**Comment by aljesusg** [comment]
Yes with some features, maybe we should launch Travis with 1.10 version too

**Pull request merged**
