### PR TITLE
SWS 155: kubernetes scripts

### PR DESCRIPTION
**Pull request by jmazzitelli**
This gets k8s deployment to work. Also includes hack scripts to get istio and bookinfo installed easily on k8s. I use minishift, but the hack scripts don't require that.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
still cleaning up and testing.. do not merge

**Comment by jmazzitelli** [comment]
tested on both OpenShift Origin 3.7 and Kubernetes/Minishift - all works. Ready for review and merge.

**Comment by jmazzitelli** [comment]
note that kubernetes issue #52787 talks about templating and they do not want to add a template feature in kubectl itself, but several people do recommend use of envsubst which is what we use in the Makefile. So we are within the mainstream.

**Comment by cfcosta** [comment]
LGTM, great work!
Tested with minikube, it worked.

**Comment by jmazzitelli** [comment]
I added some notes about this in the README. There is also a README in the hack/istio folder to help document these.

**Pull request merged**
