### PR TITLE
feat(travis): add show errors if gofmt fail

### PR DESCRIPTION
**Pull request by aljesusg**
Show in trravis the erros of gofmt.

cc @xeviknal Here is the improve ^^

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@aljesusg rebase to master and I can re-approve/merge

**Comment by jmazzitelli** [comment]
what happened? Did it go out of date again? :)

**Comment by aljesusg** [comment]
It seems by the merge of go version check...

**Comment by jmazzitelli** [comment]
someone needs to explain this to me. Why is github still saying branch is out of date when all that this PR changed was .travis.yml and nothing should conflict with this in current master. This should just merge.

Is there some setting on our project that doesn't allow a PR to merge if it isn't rebased on head of master? Because if so, that's an annoying setting.

**Pull request merged**
